#This compose file is to connect mongo express with mongodb

services:
    mongodb:
      image: mongo
      container_name: mongodb
      environment :
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      ports:
        - 27017:27017
    
    mongoexpress: 
      image: mongo-express:1.0.2-20-alpine3.19
      container_name: mongoexpress
      environment: 
        ME_CONFIG_MONGODB_SERVER: mongodb  
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}      
      ports:
        - 8081:8081
      depends_on:
        - mongodb
          